name: build

on:
  push:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: pwsh
        run: | 
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Create an exe ECGAnalyzer
        shell: pwsh
        run: pyinstaller -F ECGAnalyzer.py

      - name: Create an exe ElectricAxisCalculator
        shell: pwsh
        run: pyinstaller -F ElectricAxisCalculator.py

      - name: Zip the exe
        shell: pwsh
        run: |
          cd D:\a\ECG-Analyzer\ECG-Analyzer\dist
          7z a -tzip -r0 ..\build\ECG-Analyzer_windows.zip ElectricAxisCalculator.exe ECGAnalyzer.exe

      - name: Upload artifact ElectricAxisCalculator
        uses: actions/upload-artifact@v4
        with:
          name: 'build_windows'
          path: 'build\ECG-Analyzer_windows.zip'
          retention-days: 1


  macos-build:
    runs-on: macos-13
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Create a binary ECGAnalyzer
        run: pyinstaller -F ECGAnalyzer.py

      - name: Create a binary ElectricAxisCalculator
        run: pyinstaller -F ElectricAxisCalculator.py

      - name: Zip the binary ElectricAxisCalculator
        run: |
          ls -l
          cd /Users/runner/work/ECG-Analyzer/ECG-Analyzer/dist
          7z a -tzip -r0 ../build/ECG-Analyzer_macos.zip ElectricAxisCalculator ECGAnalyzer

      - name: Upload artifact ElectricAxisCalculator
        uses: actions/upload-artifact@v4
        with:
          name: 'build_macos'
          path: 'build/ECG-Analyzer_macos.zip'
          retention-days: 1

  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Create a binary ECGAnalyzer
        run: pyinstaller -F ECGAnalyzer.py

      - name: Create a binary ElectricAxisCalculator
        run: pyinstaller -F ElectricAxisCalculator.py

      - name: Zip the binary
        run: |
          ls -l
          cd /home/runner/work/ECG-Analyzer/ECG-Analyzer/dist
          7z a -tzip -r0 ../build/ECG-Analyzer_linux.zip ECGAnalyzer ElectricAxisCalculator

      - name: Upload artifact ElectricAxisCalculator
        uses: actions/upload-artifact@v4
        with:
          name: 'build_linux'
          path: 'build/ECG-Analyzer_linux.zip'
          retention-days: 1


  Commit-changes:
    needs: [windows-build, macos-build, linux-build]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'build: updated binaries'
          branch: main
          file_pattern: build/ECG-Analyzer_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}